#!/bin/bash

# Set the commit regex pattern

# the regex below is linux only
#commit_regex='^([A-Za-z]+-[0-9]+\s)+(#(in-progress|fixed|done)\s)?#(comment) (feat|fix|docs|style|refactor|perf|test|chore)(\(.+\))?: [A-Za-z].{1,100}$'

# the regex below is linux+windows
commit_regex='^([A-Za-z]+-[0-9]+ )+(#(in-progress|fixed|done) )?#(comment) (feat|fix|docs|style|refactor|perf|test|chore)(\(.+\))?: [A-Za-z].{1,100}$'

# Get the commit message entered by the user
commit_msg=$(cat $1)

# If the commit message does not match the regex pattern, print an error message and exit with a non-zero status code
if ! [[ $commit_msg =~ $commit_regex ]]; then
  echo "Aborting commit. Commit message does not match the conventional commit format. Please refer to https://fssplatform.atlassian.net/wiki/spaces/PEDOC/pages/90472459/Bitbucket+Commit+Message+Guide" >&2
  exit 1
fi
